//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSCopying-Protocol.h>
#import <XCTest/NSSecureCoding-Protocol.h>

@class NSString;

@interface XCAccessibilityElement : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_context;
    id _payload;
    int _processIdentifier;
    struct __AXUIElement *_axElement;
}

+ (id)deviceElement;
+ (id)elementWithAXUIElement:(struct __AXUIElement *)arg1;
+ (id)elementWithProcessIdentifier:(int)arg1;
+ (id)mockElementWithProcessIdentifier:(int)arg1;
+ (id)mockElementWithProcessIdentifier:(int)arg1 payload:(id)arg2;
+ (_Bool)supportsSecureCoding;
@property(readonly) const struct __AXUIElement *AXUIElement; // @synthesize AXUIElement=_axElement;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithAXUIElement:(struct __AXUIElement *)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMockProcessIdentifier:(int)arg1 payload:(id)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, getter=isNative) _Bool native;
@property(readonly) id payload; // @synthesize payload=_payload;
@property(readonly) int processIdentifier; // @synthesize processIdentifier=_processIdentifier;

@end

