//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface XCApplicationMonitor : NSObject
{
    NSMutableDictionary *_applicationImplementations;
    NSMutableDictionary *_applicationProcessesForPID;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedMonitor;
@property NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)terminateApplicationProcess:(id)arg1;
- (id)monitoredApplicationWithProcessIdentifier:(int)arg1;
- (void)_beginMonitoringApplication:(id)arg1;
@property(readonly, copy) NSArray *monitoredApplications;
- (void)setApplicationProcess:(id)arg1 forPID:(int)arg2;
- (id)applicationProcessWithPID:(int)arg1;
- (id)applicationImplementationForApplicationAtPath:(id)arg1 bundleID:(id)arg2;
- (id)init;

@end

