//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTest/XCApplicationMonitor.h>

@interface XCApplicationMonitor_iOS : XCApplicationMonitor
{
}

- (void)_beginMonitoringApplication:(id)arg1;
- (id)init;
- (id)monitoredApplicationWithProcessIdentifier:(int)arg1;
- (void)terminateApplicationProcess:(id)arg1;

@end

