//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSCopying-Protocol.h>

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, XCKeyboardKeyMap;

@interface XCKeyboardInputSolver : NSObject <NSCopying>
{
    XCKeyboardKeyMap *_keyMap;
    NSString *_string;
    unsigned long long _requiredFlags;
    unsigned long long _excludedFlags;
    unsigned long long _currentFlags;
    _Bool _includeModifierKeys;
    struct _NSRange _unsolvedRange;
    NSMutableArray *_solvedInputs;
    NSMutableDictionary *_solvingPaths;
}

- (id)_solve;
- (void)advancePath:(id)arg1 range:(id)arg2;
- (unsigned long long)advancePaths;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property unsigned long long currentFlags; // @synthesize currentFlags=_currentFlags;
- (void)dealloc;
@property unsigned long long excludedFlags; // @synthesize excludedFlags=_excludedFlags;
- (id)extractCompletePathsWithSolutionRange:(struct _NSRange)arg1;
@property _Bool includeModifierKeys; // @synthesize includeModifierKeys=_includeModifierKeys;
- (id)init;
- (id)initWithKeyMap:(id)arg1 string:(id)arg2;
@property(readonly, getter=isComplete) _Bool complete;
@property(readonly) XCKeyboardKeyMap *keyMap; // @synthesize keyMap=_keyMap;
@property unsigned long long requiredFlags; // @synthesize requiredFlags=_requiredFlags;
- (id)solve;
- (void)solveWithSolutionRange:(struct _NSRange)arg1 results:(id)arg2;
@property(readonly) NSArray *solvedInputs; // @synthesize solvedInputs=_solvedInputs;
@property(readonly, copy) NSString *string; // @synthesize string=_string;
@property(readonly) struct _NSRange unsolvedRange; // @synthesize unsolvedRange=_unsolvedRange;

@end

