//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSSecureCoding-Protocol.h>

@class NSArray, NSMutableArray;

@interface XCPointerEventPath : NSObject <NSSecureCoding>
{
    NSMutableArray *_pointerEvents;
    _Bool _immutable;
    unsigned long long _pathType;
    unsigned long long _index;
}

+ (_Bool)supportsSecureCoding;
- (void)_addPointerEvent:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)firstEventAfterOffset:(double)arg1;
@property _Bool immutable; // @synthesize immutable=_immutable;
@property unsigned long long index; // @synthesize index=_index;
- (id)init;
- (id)initForMouseAtPoint:(struct CGPoint)arg1 offset:(double)arg2;
- (id)initForTouchAtPoint:(struct CGPoint)arg1 offset:(double)arg2;
- (id)initWithCoder:(id)arg1;
- (id)lastEventBeforeOffset:(double)arg1;
- (void)liftUpAtOffset:(double)arg1;
- (void)moveToPoint:(struct CGPoint)arg1 atOffset:(double)arg2;
@property(readonly) unsigned long long pathType; // @synthesize pathType=_pathType;
@property(readonly) NSArray *pointerEvents;
- (void)pressButton:(unsigned long long)arg1 atOffset:(double)arg2;
- (void)pressDownAtOffset:(double)arg1;
- (void)releaseButton:(unsigned long long)arg1 atOffset:(double)arg2;

@end

