//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface XCTestContextScope : NSObject
{
    XCTestContextScope *_parentScope;
    NSMutableArray *_handlers;
}

- (void)dealloc;
@property(copy) NSMutableArray *handlers; // @synthesize handlers=_handlers;
- (id)initWithParentScope:(id)arg1;
@property(readonly) XCTestContextScope *parentScope; // @synthesize parentScope=_parentScope;

@end

