//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSSecureCoding-Protocol.h>

@interface XCTouchEvent : NSObject <NSSecureCoding>
{
    unsigned long long _touchEventType;
    double _offset;
    struct CGPoint _coordinate;
}

+ (_Bool)supportsSecureCoding;
+ (id)touchEventWithType:(unsigned long long)arg1 coordinate:(struct CGPoint)arg2 offset:(double)arg3;
@property struct CGPoint coordinate; // @synthesize coordinate=_coordinate;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property double offset; // @synthesize offset=_offset;
@property unsigned long long touchEventType; // @synthesize touchEventType=_touchEventType;

@end

