//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSSecureCoding-Protocol.h>

@class NSArray, NSMutableArray;

@interface XCTouchPath : NSObject <NSSecureCoding>
{
    NSMutableArray *_touchEvents;
    _Bool _immutable;
    unsigned long long _index;
    long long _interfaceOrientation;
}

+ (_Bool)supportsSecureCoding;
- (void)_addTouchEvent:(id)arg1;
@property(readonly) _Bool complete;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)firstEventAfterOffset:(double)arg1;
@property _Bool immutable; // @synthesize immutable=_immutable;
@property unsigned long long index; // @synthesize index=_index;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithTouchDown:(struct CGPoint)arg1 orientation:(long long)arg2 offset:(double)arg3;
@property(readonly) long long interfaceOrientation; // @synthesize interfaceOrientation=_interfaceOrientation;
- (id)lastEventBeforeOffset:(double)arg1;
- (void)liftUpAtPoint:(struct CGPoint)arg1 offset:(double)arg2;
- (void)moveToPoint:(struct CGPoint)arg1 atOffset:(double)arg2;
@property(readonly) NSArray *touchEvents;

@end

