//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTest/XCUIElement.h>

@class NSArray, NSDictionary, NSString, XCAccessibilityElement, XCApplicationQuery, XCUIApplicationImpl;

@interface XCUIApplication : XCUIElement
{
    _Bool _ancillary;
    XCUIElement *_keyboard;
    NSArray *_launchArguments;
    NSDictionary *_launchEnvironment;
    XCUIApplicationImpl *_applicationImpl;
    XCApplicationQuery *_applicationQuery;
    unsigned long long _generation;
}

+ (id)appWithPID:(int)arg1;
+ (id)keyPathsForValuesAffectingRunning;
- (void)_launchUsingXcode:(_Bool)arg1;
- (void)_waitForQuiescence;
- (void)_waitForViewControllerViewDidDisappearWithTimeout:(double)arg1;
@property(readonly) XCAccessibilityElement *accessibilityElement;
@property _Bool ancillary; // @synthesize ancillary=_ancillary;
- (id)application;
@property(readonly) XCUIApplicationImpl *applicationImpl; // @synthesize applicationImpl=_applicationImpl;
@property(retain) XCApplicationQuery *applicationQuery; // @synthesize applicationQuery=_applicationQuery;
@property(readonly) NSString *bundleID;
- (void)clearQuery;
- (void)dealloc;
- (id)description;
- (void)dismissKeyboard;
- (unsigned long long)elementType;
@property unsigned long long generation; // @synthesize generation=_generation;
- (id)init;
- (id)initPrivateWithPath:(id)arg1 bundleID:(id)arg2;
@property(readonly, nonatomic) long long interfaceOrientation;
@property(readonly) XCUIElement *keyboard; // @synthesize keyboard=_keyboard;
- (id)lastSnapshot;
- (void)launch;
@property(copy, nonatomic) NSArray *launchArguments; // @synthesize launchArguments=_launchArguments;
@property(copy, nonatomic) NSDictionary *launchEnvironment; // @synthesize launchEnvironment=_launchEnvironment;
@property(readonly) NSString *path;
@property(nonatomic) int processID;
- (id)query;
@property(readonly, nonatomic) _Bool running;
@property(nonatomic) unsigned long long state;
- (void)terminate;

@end

