//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/NSCopying-Protocol.h>

@class XCUIElement;

@interface XCUICoordinate : NSObject <NSCopying>
{
    XCUIElement *_element;
    XCUICoordinate *_coordinate;
    struct CGVector _normalizedOffset;
    struct CGVector _pointsOffset;
}

@property(readonly) XCUICoordinate *coordinate; // @synthesize coordinate=_coordinate;
- (id)coordinateWithOffset:(struct CGVector)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (void)doubleTap;
@property(readonly) XCUIElement *element; // @synthesize element=_element;
- (id)init;
- (id)initWithCoordinate:(id)arg1 pointsOffset:(struct CGVector)arg2;
- (id)initWithElement:(id)arg1 normalizedOffset:(struct CGVector)arg2;
@property(readonly) struct CGVector normalizedOffset; // @synthesize normalizedOffset=_normalizedOffset;
@property(readonly) struct CGVector pointsOffset; // @synthesize pointsOffset=_pointsOffset;
- (void)pressForDuration:(double)arg1;
- (void)pressForDuration:(double)arg1 thenDragToCoordinate:(id)arg2;
@property(readonly) XCUIElement *referencedElement;
@property(readonly) struct CGPoint screenPoint;
- (void)tap;

@end

