//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, XCTest;

@interface _XCInternalTestRun : NSObject
{
    XCTest *_test;
    double _startTimeInterval;
    double _stopTimeInterval;
    unsigned long long _executionCount;
    unsigned long long _failureCount;
    unsigned long long _unexpectedExceptionCount;
    _Bool _hasStarted;
    _Bool _hasStopped;
}

- (void)dealloc;
@property(readonly) unsigned long long executionCount;
@property(readonly) unsigned long long failureCount;
@property(readonly) _Bool hasStopped; // @synthesize hasStopped=_hasStopped;
- (id)initWithTest:(id)arg1;
- (void)recordFailureWithDescription:(id)arg1 inFile:(id)arg2 atLine:(unsigned long long)arg3 expected:(_Bool)arg4;
- (void)start;
@property(readonly, copy) NSDate *startDate;
- (void)stop;
@property(readonly, copy) NSDate *stopDate;
@property(readonly) XCTest *test; // @synthesize test=_test;
@property(readonly) unsigned long long testCaseCount;
@property(readonly) double testDuration;
@property(readonly) double totalDuration;
@property(readonly) unsigned long long unexpectedExceptionCount;

@end

