//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTest/XCTestExpectation.h>

@class NSPredicate, NSTimer;

@interface _XCPredicateExpectation : XCTestExpectation
{
    id _object;
    NSPredicate *_predicate;
    CDUnknownBlockType _handler;
    NSTimer *_timer;
}

- (void)_considerFulfilling;
- (void)dealloc;
@property(copy) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain) id object; // @synthesize object=_object;
@property(copy) NSPredicate *predicate; // @synthesize predicate=_predicate;
- (void)startObserving;

@end

