//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTest/XCUIElementQuery.h>

@class XCElementSnapshot, XCUIApplication;

@interface XCApplicationQuery : XCUIElementQuery
{
    XCUIApplication *_application;
    XCElementSnapshot *_lastSnapshot;
}

- (id)application;
- (void)dealloc;
- (id)initWithApplication:(id)arg1;
@property(retain) XCElementSnapshot *lastSnapshot; // @synthesize lastSnapshot=_lastSnapshot;
- (id)matchingSnapshotsWithError:(id *)arg1;

@end

