//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTest/XCTest.h>

@class NSInvocation, XCTestCaseRun, XCTestContext, _XCTestCaseImplementation;

@interface XCTestCase : XCTest
{
    id _internalImplementation;
}

+ (void)_allTestMethodInvocations:(id)arg1;
+ (id)_baselineDictionary;
+ (_Bool)_enableSymbolication;
+ (_Bool)_reportPerformanceFailuresForLargeImprovements;
+ (_Bool)_treatMissingBaselinesAsTestFailures;
+ (id)allSubclasses;
+ (id)allTestMethodInvocations;
+ (id)defaultPerformanceMetrics;
+ (id)defaultTestSuite;
+ (_Bool)isInheritingTestCases;
+ (void)setUp;
+ (void)tearDown;
+ (id)testCaseWithInvocation:(id)arg1;
+ (id)testCaseWithSelector:(SEL)arg1;
+ (id)testInvocations;
+ (id)testMethodInvocations;
- (void)_completeWithResult:(id)arg1;
- (void)_configureTimeoutForInterval:(double)arg1 forWaitAtAddress:(unsigned long long)arg2 testClassName:(id)arg3 testMethodName:(id)arg4;
- (void)_dequeueFailures;
- (_Bool)_didMeasureMetrics;
- (_Bool)_didStartMeasuring;
- (_Bool)_didStopMeasuring;
- (void)_enqueueFailureWithDescription:(id)arg1 inFile:(id)arg2 atLine:(unsigned long long)arg3 expected:(_Bool)arg4;
- (id)_expectationForDarwinNotification:(id)arg1;
- (_Bool)_expectationsHaveBeenFulfilled;
- (void)_fulfillExpectation:(id)arg1;
- (void)_interruptTest;
- (_Bool)_isMeasuringMetrics;
- (void)_logAndReportPerformanceMetrics:(id)arg1 perfMetricResultsForIDs:(id)arg2 withBaselinesForTest:(id)arg3 defaultBaselinesForPerfMetricID:(id)arg4;
- (id)_perfMetricDataForID;
- (void)_recordUnexpectedFailureWithDescription:(id)arg1 exception:(id)arg2;
- (void)_recordValues:(id)arg1 forPerformanceMetricID:(id)arg2 name:(id)arg3 unitsOfMeasurement:(id)arg4 baselineName:(id)arg5 baselineAverage:(id)arg6 maxPercentRegression:(id)arg7 maxPercentRelativeStandardDeviation:(id)arg8 maxRegression:(id)arg9 maxStandardDeviation:(id)arg10 file:(id)arg11 line:(unsigned long long)arg12;
- (Class)_requiredTestRunBaseClass;
- (id)_symbolicationRecordForTestCodeInAddressStack:(id)arg1;
@property(readonly) unsigned long long activityRecordStackDepth;
- (id)addUIInterruptionMonitorWithDescription:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)afterTestIteration:(unsigned long long)arg1 selector:(SEL)arg2;
- (void)beforeTestIteration:(unsigned long long)arg1 selector:(SEL)arg2;
@property _Bool continueAfterFailure;
- (void)dealloc;
- (id)description;
- (id)expectationForNotification:(id)arg1 object:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)expectationForPredicate:(id)arg1 evaluatedWithObject:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)expectationWithDescription:(id)arg1;
- (id)init;
- (id)initWithInvocation:(id)arg1;
- (id)initWithSelector:(SEL)arg1;
@property(retain) _XCTestCaseImplementation *internalImplementation; // @synthesize internalImplementation=_internalImplementation;
@property(retain) NSInvocation *invocation;
- (void)invokeTest;
- (_Bool)isEqual:(id)arg1;
- (id)keyValueObservingExpectationForObject:(id)arg1 keyPath:(id)arg2 expectedValue:(id)arg3;
- (id)keyValueObservingExpectationForObject:(id)arg1 keyPath:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)languageAgnosticTestMethodName;
- (void)measureBlock:(CDUnknownBlockType)arg1;
- (void)measureMetrics:(id)arg1 automaticallyStartMeasuring:(_Bool)arg2 forBlock:(CDUnknownBlockType)arg3;
- (id)name;
- (id)nameForLegacyLogging;
- (unsigned long long)numberOfTestIterationsForTestWithSelector:(SEL)arg1;
- (void)performTest:(id)arg1;
- (void)recordFailureWithDescription:(id)arg1 inFile:(id)arg2 atLine:(unsigned long long)arg3 expected:(_Bool)arg4;
- (void)removeUIInterruptionMonitor:(id)arg1;
@property(nonatomic) _Bool shouldHaltWhenReceivesControl;
@property(retain) XCTestCaseRun *testCaseRun;
- (void)setUpTestWithSelector:(SEL)arg1;
- (void)startActivityWithTitle:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)startMeasuring;
- (void)stopMeasuring;
- (void)tearDownTestWithSelector:(SEL)arg1;
- (unsigned long long)testCaseCount;
@property(readonly) XCTestContext *testContext;
- (Class)testRunClass;
- (void)waitForExpectationsWithTimeout:(double)arg1 handler:(CDUnknownBlockType)arg2;

@end

