//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, XCTestRun;

@interface XCTest : NSObject
{
    id _internal;
}

+ (id)languageAgnosticTestClassNameForTestClass:(Class)arg1;
@property(readonly) NSString *_classNameForReporting;
@property(readonly) NSString *_methodNameForReporting;
@property(readonly) Class _requiredTestRunBaseClass;
- (void)dealloc;
- (id)init;
@property(readonly) NSString *languageAgnosticTestClassName;
@property(readonly) NSString *languageAgnosticTestMethodName;
@property(readonly, copy) NSString *name;
@property(readonly) NSString *nameForLegacyLogging;
- (void)performTest:(id)arg1;
- (void)removeTestsWithNames:(id)arg1;
- (id)run;
- (void)runTest;
- (void)setUp;
- (void)tearDown;
@property(readonly) unsigned long long testCaseCount;
@property(readonly) XCTestRun *testRun;
@property(readonly) Class testRunClass;

@end

