//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XCTest/XCUIElementAttributes-Protocol.h>
#import <XCTest/XCUIElementTypeQueryProvider-Protocol.h>

@class NSString, XCElementSnapshot, XCUIApplication, XCUIElementQuery;

@interface XCUIElement : NSObject <XCUIElementAttributes, XCUIElementTypeQueryProvider>
{
    _Bool _safeQueryResolutionEnabled;
    XCUIElementQuery *_query;
    XCElementSnapshot *_lastSnapshot;
}

- (void)_dispatchEvent:(id)arg1 block:(CDUnknownBlockType)arg2;
- (struct CGPoint)_hitPointByAttemptingToScrollToVisibleSnapshot:(id)arg1;
@property(readonly, copy) XCUIElementQuery *activityIndicators;
- (void)adjustToNormalizedSliderPosition:(double)arg1;
- (void)adjustToPickerWheelValue:(id)arg1;
@property(readonly, copy) XCUIElementQuery *alerts;
@property(readonly, nonatomic) XCUIApplication *application;
@property(readonly, copy) XCUIElementQuery *browsers;
@property(readonly, copy) XCUIElementQuery *buttons;
@property(readonly, copy) XCUIElementQuery *cells;
@property(readonly, copy) XCUIElementQuery *checkBoxes;
- (id)childrenMatchingType:(unsigned long long)arg1;
@property(readonly, copy) XCUIElementQuery *collectionViews;
@property(readonly, copy) XCUIElementQuery *colorWells;
@property(readonly, copy) XCUIElementQuery *comboBoxes;
- (id)coordinateWithNormalizedOffset:(struct CGVector)arg1;
@property(readonly, copy) XCUIElementQuery *datePickers;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) XCUIElementQuery *decrementArrows;
- (id)descendantsMatchingType:(unsigned long long)arg1;
- (id)description;
@property(readonly, copy) XCUIElementQuery *dialogs;
@property(readonly, copy) XCUIElementQuery *disclosureTriangles;
@property(readonly, copy) XCUIElementQuery *dockItems;
- (void)doubleTap;
@property(readonly, copy) XCUIElementQuery *drawers;
@property(readonly) unsigned long long elementType;
@property(readonly) _Bool exists;
@property(readonly) struct CGRect frame;
@property(readonly, copy) XCUIElementQuery *grids;
@property(readonly, copy) XCUIElementQuery *groups;
@property(readonly, copy) XCUIElementQuery *handles;
@property(readonly) _Bool hasKeyboardFocus;
@property(readonly, copy) XCUIElementQuery *helpTags;
- (id)hitPointCoordinate;
@property(readonly) long long horizontalSizeClass;
@property(readonly, copy) XCUIElementQuery *icons;
@property(readonly) NSString *identifier;
@property(readonly, copy) XCUIElementQuery *images;
@property(readonly, copy) XCUIElementQuery *incrementArrows;
- (id)initWithElementQuery:(id)arg1;
@property(readonly, nonatomic) long long interfaceOrientation;
@property(readonly, getter=isEnabled) _Bool enabled;
@property(readonly, getter=isHittable) _Bool hittable;
@property(readonly, getter=isSelected) _Bool selected;
@property(readonly, copy) XCUIElementQuery *keyboards;
@property(readonly, copy) XCUIElementQuery *keys;
@property(readonly, copy) NSString *label;
@property(retain) XCElementSnapshot *lastSnapshot; // @synthesize lastSnapshot=_lastSnapshot;
@property(readonly, copy) XCUIElementQuery *layoutAreas;
@property(readonly, copy) XCUIElementQuery *layoutItems;
@property(readonly, copy) XCUIElementQuery *levelIndicators;
@property(readonly, copy) XCUIElementQuery *links;
@property(readonly, copy) XCUIElementQuery *maps;
@property(readonly, copy) XCUIElementQuery *mattes;
@property(readonly, copy) XCUIElementQuery *menuBarItems;
@property(readonly, copy) XCUIElementQuery *menuBars;
@property(readonly, copy) XCUIElementQuery *menuButtons;
@property(readonly, copy) XCUIElementQuery *menuItems;
@property(readonly, copy) XCUIElementQuery *menus;
@property(readonly, copy) XCUIElementQuery *navigationBars;
@property(readonly) double normalizedSliderPosition;
@property(readonly, copy) XCUIElementQuery *otherElements;
@property(readonly, copy) XCUIElementQuery *outlineRows;
@property(readonly, copy) XCUIElementQuery *outlines;
@property(readonly, copy) XCUIElementQuery *pageIndicators;
@property(readonly, copy) XCUIElementQuery *pickerWheels;
@property(readonly, copy) XCUIElementQuery *pickers;
- (void)pinchWithScale:(double)arg1 velocity:(double)arg2;
@property(readonly) NSString *placeholderValue;
@property(readonly, copy) XCUIElementQuery *popUpButtons;
@property(readonly, copy) XCUIElementQuery *popovers;
- (void)pressForDuration:(double)arg1;
- (void)pressForDuration:(double)arg1 thenDragToElement:(id)arg2;
@property(readonly, copy) XCUIElementQuery *progressIndicators;
@property(readonly) XCUIElementQuery *query; // @synthesize query=_query;
@property(readonly, copy) XCUIElementQuery *radioButtons;
@property(readonly, copy) XCUIElementQuery *radioGroups;
@property(readonly, copy) XCUIElementQuery *ratingIndicators;
@property(readonly, copy) XCUIElementQuery *relevanceIndicators;
- (void)resolve;
- (void)resolveHandleUIInterruption:(_Bool)arg1;
- (void)rotate:(double)arg1 withVelocity:(double)arg2;
@property(readonly, copy) XCUIElementQuery *rulerMarkers;
@property(readonly, copy) XCUIElementQuery *rulers;
@property _Bool safeQueryResolutionEnabled; // @synthesize safeQueryResolutionEnabled=_safeQueryResolutionEnabled;
@property(readonly, copy) XCUIElementQuery *scrollBars;
@property(readonly, copy) XCUIElementQuery *scrollViews;
@property(readonly, copy) XCUIElementQuery *searchFields;
@property(readonly, copy) XCUIElementQuery *secureTextFields;
@property(readonly, copy) XCUIElementQuery *segmentedControls;
@property(readonly, copy) XCUIElementQuery *sheets;
@property(readonly, copy) XCUIElementQuery *sliders;
@property(readonly, copy) XCUIElementQuery *splitGroups;
@property(readonly, copy) XCUIElementQuery *splitters;
@property(readonly, copy) XCUIElementQuery *staticTexts;
@property(readonly, copy) XCUIElementQuery *statusBars;
@property(readonly, copy) XCUIElementQuery *steppers;
- (void)swipeDown;
- (void)swipeLeft;
- (void)swipeRight;
- (void)swipeUp;
@property(readonly, copy) XCUIElementQuery *switches;
@property(readonly, copy) XCUIElementQuery *tabBars;
@property(readonly, copy) XCUIElementQuery *tabGroups;
@property(readonly, copy) XCUIElementQuery *tableColumns;
@property(readonly, copy) XCUIElementQuery *tableRows;
@property(readonly, copy) XCUIElementQuery *tables;
@property(readonly, copy) XCUIElementQuery *tabs;
- (void)tap;
- (void)tapWithNumberOfTaps:(unsigned long long)arg1 numberOfTouches:(unsigned long long)arg2;
@property(readonly, copy) XCUIElementQuery *textFields;
@property(readonly, copy) XCUIElementQuery *textViews;
@property(readonly, copy) XCUIElementQuery *timelines;
@property(readonly, copy) NSString *title;
@property(readonly, copy) XCUIElementQuery *toggles;
@property(readonly, copy) XCUIElementQuery *toolbarButtons;
@property(readonly, copy) XCUIElementQuery *toolbars;
- (unsigned long long)traits;
- (void)twoFingerTap;
- (void)typeText:(id)arg1;
@property(readonly) id value;
@property(readonly, copy) XCUIElementQuery *valueIndicators;
@property(readonly) long long verticalSizeClass;
@property(readonly, copy) XCUIElementQuery *webViews;
@property(readonly, copy) XCUIElementQuery *windows;

@end

