//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec  8 2015 15:34:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCTest/XCUICoordinate.h>

@interface XCUIElementHitPointCoordinate : XCUICoordinate
{
}

- (id)description;
- (id)initWithCoordinate:(id)arg1 pointsOffset:(struct CGVector)arg2;
- (id)initWithElement:(id)arg1;
- (id)initWithElement:(id)arg1 normalizedOffset:(struct CGVector)arg2;
- (struct CGPoint)screenPoint;

@end

